Repository artsenius/test-automation-webdriverio-qa3, pull requests merged in 2019-05, with the labels that each got.

#16 tuzov-forgot-password-back-button
  test/expected/forgot-password.js
  test/selectors/forgot-password.js
  test/specs/reg/forgot-password.js
  wdio.conf.js
Labels: APPROVED

#17 RBTA-88/atambayev-daulet/navigation-bar/general
  test/expected/navigation.js
  test/selectors/navigation-bar.js
  test/specs/reg/navigationBar/general-nav-bar.js
  wdio.conf.js
Labels: CHANGES_REQUIRED, DO_NOT_MERGE, MERGE_CONFLICTS

#25 Rbta 90/volodymyr cherniak/login/required field text
  test/expected/login.js
  test/selectors/login.js
  test/specs/reg/login/general.js
  wdio.conf.js
Labels: APPROVED

#26 RBTA-95-bug-report-edit-mode-input-fields-kiparisova
  test/expected/bug-report.js
  test/selectors/bug-report.js
  test/specs/reg/bug-report/edit-mode-.js
  test/specs/reg/login.js
  wdio.conf.js
Labels: APPROVED

#22 RBTA-92/kharkova/Create tests for Filter Bar functionality
  test/expected/filter-bar.js
  test/helpers/filter-bar.js
  test/selectors/filter-bar.js
  test/specs/reg/filter-bar/functionality.js
  wdio.conf.js
Labels: APPROVED

#33 RBTA-96/bug-report-edit-mode-text-area/kiparisova
  test/specs/reg/bug-report/edit-mode-.js
Labels: APPROVED

#30 RBTA-36-forgot-password/error-design/error location check/trusevich
  test/selectors/forgot-password.js
  test/specs/reg/forgot-password/design.js
Labels: APPROVED, MERGE_CONFLICTS

#23 RBTA-53-registration-email/password check-trusevich
  test/data/registration.js
  test/expected/registration.js
  test/selectors/registration.js
  test/specs/reg/registration/email-password-check.js
Labels: APPROVED, DONE

#28 RBTA-36/forgot password design/priadka
  test/expected/forgot-password.js
  test/specs/reg/forgot-password/design.js
  wdio.conf.js
Labels: APPROVED, MERGE_CONFLICTS

#37 Registration Last Name placeholder
  package-lock.json
  test/expected/registration.js
  test/specs/reg/registration/general.js
  wdio.conf.js
Labels: APPROVED

#32 Rbta-100/casim/bug report/comments title
  test/expected/bug-report-comments.js
  test/selectors/bug-report.js
  test/specs/reg/bug-report/comments.js
Labels: APPROVED

#29 RBTA-42/RBTA-43/registration/general/confirm_email&password
  test/data/registration.js
  test/expected/registration.js
  test/helpers/helpers.js
  test/specs/reg/registration/general.js
Labels: CHANGES_REQUIRED, DO_NOT_MERGE, NEEDS_CONSULTATION

#41 Fix - registration-email-password-check
  test/specs/reg/registration/email-password-check.js
Labels: APPROVED

#42 Cherniak volodymyr/login/general/forgot password/little change
  test/expected/login.js
  test/specs/reg/login/general.js
Labels: APPROVED

#44 Registration/functionality/first&last name
  test/data/registration.js
  test/expected/registration.js
  test/specs/reg/registration/functionality.js
Labels: APPROVED

#45 RBTA-111-112/kharkova/Create tests for bug report disable state (titles and values)
  test/expected/bug-report.js
  test/selectors/bug-report.js
  test/specs/reg/bug-report/disabled-state.js
Labels: DONE

#34 RBTA-140/bug-form-buttons/frankiv
  test/expected/bug-form.js
  test/selectors/bug-form.js
  test/specs/reg/bug-form/bug-form-buttons.js
Labels: CHANGES_REQUIRED, DONE, DO_NOT_MERGE

#36 Functionality tests for Email login are done.
  test/expected/login.js
  test/helpers/helpers.js
  test/selectors/login.js
  test/specs/reg/login/functionality.js
Labels: CHANGES_REQUIRED, DONE, DO_NOT_MERGE, MERGE_CONFLICTS

#46 General Email
  test/expected/login.js
  test/specs/reg/login/general.js
Labels: CHANGES_REQUIRED, DO_NOT_MERGE

#43 RTBA-142/nikiforov/bug-form/functionality/text-fields
  test/expected/bug-form.js
  test/helpers/helpers.js
  test/selectors/bug-form.js
  test/selectors/bug-list.js
  test/selectors/bugList.js
  test/specs/reg/bug-form/functionality.js
  test/specs/reg/bug-list/bug-search.js
  test/specs/reg/bug-list/status-badges.js
Labels: CHANGES_REQUIRED, DONE, DO_NOT_MERGE

#24 RBTA-22-login-functionality-registration-kashina
  test/selectors/client.js
  test/selectors/login.js
  test/specs/reg/login/functionality.js
Labels: CHANGES_REQUIRED, DO_NOT_MERGE, MERGE_CONFLICTS

#14 I wrote a tests login general
  package-lock.json
  test/selectors/login.js
  test/specs/reg/login/general.js
Labels: CHANGES_REQUIRED, DO_NOT_MERGE, MERGE_CONFLICTS

#47 RBTA-98/bug-report/control-bar-edit-mode-cancel-button/kiparisova
  test/expected/bug-report.js
  test/helpers/helpers.js
  test/selectors/bug-report.js
  test/specs/reg/bug-report/control-bar-edit-mode.js
Labels: DONE

#59 RBTA-17/login/general/login button/aliakseyeva
  test/expected/login.js
  test/specs/reg/login/general.js
Labels: DONE

#60 RBTA-30, 31, 32/Tuzov/forgot-password
  test/expected/forgot-password.js
  test/specs/reg/forgot-password.js
  test/specs/reg/forgot-password/general.js
Labels: APPROVED, DONE

#56 RTBA-65/nikiforov/bug-list/de sign-functionality
  test/expected/bug-list.js
  test/expected/filter-bar.js
  test/helpers/helpers.js
  test/selectors/bug-list.js
  test/selectors/filter-bar.js
  test/specs/reg/bug-list/bug-search.js
  test/specs/reg/bug-list/design.js
  test/specs/reg/bug-list/pop-up.js
  test/specs/reg/filter-bar/design.js
  test/specs/reg/filter-bar/general.js
Labels: DONE

#55 RBTA-121/122/123/bug report control bar default state/status badge/edit button/kolosok
  .DS_Store
  .gitignore
  test/.DS_Store
  test/expected/bug-report.js
  test/selectors/bug-report.js
  test/specs/reg/bug-report/control-bar.js
  test/specs/reg/bug-report/edit-mode.js
Labels: DONE

#65 Fields validation without user registration based on Arthur comments
  test/expected/registration.js
  test/specs/reg/registration/functionality.js
  test/specs/reg/registration/general.js
Labels: APPROVED, DONE

#49 RBTA-99/bug report/comments/general/volodymyr-cherniak
  test/expected/bug-report-comments.js
  test/helpers/comments.js
  test/selectors/bug-report.js
  test/specs/reg/bug-report/comments.js
Labels: DONE

#68 RBTA-85/bug-form/text-fields/expected-result/aliakseyeva
  test/expected/bug-form.js
  test/specs/reg/bug-form/text-fields.js
Labels: DONE

#48 Comments list of comments empty
  .gitignore
  test/expected/bug-report-comments.js
  test/helpers/helpers.js
  test/selectors/bug-report.js
  test/specs/reg/bug-report/comments.js
Labels: APPROVED, DONE

#50 Origin/bug form/summary
  test/expected/bug-form.js
  test/selectors/bug-form.js
  test/specs/reg/bug-form/summary.js
Labels: DONE

#70 RTBA-165/nikiforov/nav-bar/loguot
  test/expected/bug-form.js
  test/selectors/bug-form.js
  test/selectors/navigation-bar.js
  test/selectors/registration.js
  test/specs/reg/bug-form/bug-form-buttons.js
  test/specs/reg/bug-form/functionality.js
  test/specs/reg/bug-form/text-fields.js
  test/specs/reg/bug-list/bug-search.js
  test/specs/reg/navigationBar/general-nav-bar.js
  test/specs/reg/navigationBar/logout.js
Labels: DONE

#78 nikiforov/Screenshots base page + delete hardcode
  test/selectors/compare.js
  test/specs/images/compare.js
Labels: DONE

#54 created tests for bug-form actual results
  package-lock.json
  test/expected/bug-form.js
  test/specs/reg/bug-form/actual-result.js
Labels: APPROVED, DONE

#64 RBTA - 114/115/116/grebneva/bug-form-functionality (Version, Dropdowns, Buttons)
  test/data/bug-form-functionality.js
  test/expected/bug-form-functionality.js
  test/helpers/bug-form-functionality.js
  test/selectors/bug-form-functionality.js
  test/specs/reg/bug-form/bug-form-buttons-dropdowns.js
  test/specs/reg/bug-form/bug-form-functionality.js
Labels: CHANGES_REQUIRED, DONE, DO_NOT_MERGE
